# https://taskfile.dev

version: '3'

tasks:
  run:
    cmds:
      - pnpm start
  build:
    cmds:
      - pnpm build
  docker-build:
    cmds:
      - docker build . -t angular-indexdb-starter:latest
  docker-run:
    cmds:
      - docker run -p 4001:4001 --rm angular-indexdb-starter:latest
    silent: true