# https://taskfile.dev

version: '3'

tasks:
  run:
    cmds:
      - pnpm start
  build:
    cmds:
      - pnpm build
  dcu:
    cmds:
      - docker compose up --build
  dcd:
    cmds:
      - docker compose down
  docker-build:
    cmds:
      - docker build . -t angular-indexdb-starter:latest
  docker-run:
    cmds:
      - docker run -p 4001:4001 --rm angular-indexdb-starter:latest
    silent: true